[config]
default_to_workspace = false
load_cargo_aliases = true

[tasks.default]
alias = "build"

[tasks.watch]
dependencies = ["check"]
run_task = { name = ["editor"], parallel = false }
watch = true

[tasks.editor]
command = "cargo"
args = ["run", "--features", "editor"]

[tasks.watch-test]
dependencies = ["check"]
run_task = { name = ["nextest"], parallel = false }
watch = true

[tasks.check]
command = "cargo"
args = ["check", "--workspace"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--allow-dirty", "--fix"]

[tasks.nextest]
command = "cargo"
args = ["nextest", "--workspace"]

[tasks.docs-deps]
script = '''
cargo doc --no-deps --target-dir /Volumes/Corsair/cargo-cache/target $({
    cargo tree -p bevy --depth 3 --format "{p}" --prefix none
    cargo tree --workspace --depth 1 --format "{p}" --prefix none
  } \
  | sed -E 's/^[^A-Za-z0-9_-]*//' \
  | sed -E 's/^([A-Za-z0-9_-]+).*/-p \1/' \
  | sort -u)
'''

[tasks.docs-own]
script = "cargo doc --workspace --all-features --no-deps --document-private-items --target-dir /Volumes/Corsair/cargo-cache/target"

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all"]

[tasks.test-build]
run_task = { name = ["nextest", "build"], parallel = false }

[tasks.do-docs]
run_task = { name = ["docs-deps", "docs-own"], parallel = false }

[tasks.lint]
run_task = { name = ["check", "clippy", "fmt"], parallel = false }

[tasks.build-all]
run_task = { name = ["test-build", "do-docs"], parallel = false }

[tasks.precommit]
run_task = { name = ["lint", "build-all"], parallel = false }

[tasks.build]
command = "cargo"
args = ["build", "--features", "editor"]

[tasks.cranelift]
script = "RUSTFLAGS=-Zcodegen-backend=cranelift cargo +nightly build"
