[alias]
make = ["bin", "cargo-make"]
nextest = ["bin", "cargo-nextest", "run", "--no-fail-fast"]
remove = ["bin", "cargo-rm"]
upgrade-local = ["bin", "cargo-upgrade", "--verbose"]
watch = ["bin", "cargo-watch"]
dx = ["bin", "dx", "serve", "--hot-patch"]
test-docs = ["test", "--workspace", "--doc"]

[build]
target-dir = "/Volumes/Corsair/cargo-cache/target"
