[package]
name = "bevy_ui_html"
version = "0.0.2"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bevy.workspace = true
bevy_ui_html_macro.workspace = true

[lints]
workspace = true

[features]
# Auto propagates values that are typically propagated in CSS
propagate = ["bevy_ui_html_macro/propagate"]
# Allows Bevy Feathers usage for additional Elements
feathers = ["bevy_ui_html_macro/feathers"]
