[package]
name = "planetes_editor"
version = "0.0.2"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { workspace = true, features = ["bevy_feathers"] }
bevy_file_dialog.workspace = true
bevy_ui_html.workspace = true
planetes_scene_state.workspace = true
planetes_input.workspace = true
avian3d = { workspace = true, optional = true }
serde.workspace = true


[features]
# feature for avian3d support
avian = ["avian3d"]

[lints]
workspace = true
